### ISSUE TITLE
Location data.

### ISSUE THREAD

**Issue by monarch434** [ktrout17/Matcha#24]
- Extended data doesn't fill in location data and when editing profile. Might be a browser security I have because location data saves when using incognito mode.

**Comment by Deathshadowown** [comment]
I Seem to get location on both fire fox and Microsoft Edge, only displaying South Africa, if that is correct, on the correct web browser and not incognito.

**Comment by ktrout17** [comment]
It's supposed to display city, province and country

**Comment by monarch434** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

I think this might be the issue. So theres nothing wrong with the code, it could be a browser plugin or ad blocker.

**Comment by ktrout17** [comment]
Closing this as there is nothing much we can do about it at this point.
