### ISSUE TITLE
Things I'm not sure about.

### ISSUE THREAD

**Issue by monarch434** [ktrout17/Matcha#26]
- For suggested matches:
1. Should fame be set to max to find people with a max rating or to the users current max rating for better results. - current user and less (fixed)

- Should the user be able to change his or her password in the edit profile page? (fixed)

**Comment by ktrout17** [comment]
Asked around:

- filter suggested matchas and advanced search results 
- blocked users shouldn't appear in search (by username)
- point system for sorting suggested matchas from best match to worst match

**Comment by Deathshadowown** [comment]
Can we Unlike a user? i tested it but i don't think so
